import {
	duna,
	ellaAndTheBlackJaguar,
	oppenheimer,
	wonka,
} from '../../../assets'

interface ICard {
	id: number
	title: string
	image: string
	countryOfOrigin?: string
	rating?: number
	collection?: {
		name?: string
	}
}

export const categorySelectionList: ICard[] = [
	{ id: 1, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 2,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 3,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 4,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 5, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 6,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 7,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 8,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 9, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 10,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 11,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 12,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 13, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 14,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 15,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 16,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 17, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 18,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 19,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 20,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 21, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 22,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 23,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 24,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 25, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 26,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 27,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 28,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 29, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 30,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 31,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 32,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 33, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 34,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 35,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 36,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 37, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 38,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 39,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 40,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 41, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 42,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 43,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 44,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 45, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 46,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 47,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 48,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 49, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 50,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 51,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 52,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 53, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 54,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 55,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 56,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 57, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 58,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 59,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 60,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 61, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 62,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 63,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 64,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 65, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 66,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 67,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 68,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 70, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 71,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 72,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 73,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 74, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 75,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 76,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 77,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 78, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 79,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 80,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 81,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 82, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 83,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 84,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 85,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 86, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 87,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 88,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 89,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 90, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 91,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 92,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 93,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 94, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 95,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 96,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 97,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 98, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 99,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 100,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 101,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 102, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 103,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 104,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 105,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 106, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 107,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 108,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 109,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 110, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 111,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 112,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 113,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 114, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 115,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 116,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 117,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 118, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 119,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 120,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 121,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 122, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 123,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 124,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 125,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 126, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 127,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 128,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 129,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 130, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 131,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 132,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 133,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 134, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 135,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 136,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 137,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 138, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 139,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 140,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 141,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 142, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 143,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 144,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 145,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},

	{ id: 146, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 147,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 148,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 149,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 150, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 151,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 152,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 153,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 154, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 155,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 156,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 157,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
	{ id: 158, title: 'Дюна', image: duna, countryOfOrigin: '2021, США, Канада' },
	{
		id: 159,
		title: 'Оппенгеймер',
		image: oppenheimer,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 160,
		title: 'Вонка',
		image: wonka,
		countryOfOrigin: '2023, США, Великобритания',
	},
	{
		id: 161,
		title: 'Элла и черный ягуар',
		image: ellaAndTheBlackJaguar,
		countryOfOrigin: '2024, Франция, Германия',
	},
]
